### ISSUE TITLE
Error when adding plots

### ISSUE THREAD

**Issue by yjiangnan** [hulatang/ceres-combineharvester#13]
I follow these steps:
git clone https://github.com/hulatang/ceres-combineharvester.git
cd ceres-combineharvester/
sudo chmod +x install.sh
./install.sh
. ./activate
ceres init
vim ~/.ceres/mainnet/config/coins_config.yaml       # uncomment -flax
ceres init --coins
ceres generate_ssl

Then, when I try to add plot directory, I get KeyError for "plot_directories":
ceres coin plots add -d /plots/$dir
```
Unable to check permissions for /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.crt: file /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.crt does not exist
Unable to check permissions for /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.crt: file /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.crt does not exist
Unable to check permissions for /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.key: file /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.key does not exist
Unable to check permissions for /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.key: file /home/dong/.ceres/mainnet/config/ssl/ca/chia_ca.key does not exist
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@             WARNING: UNPROTECTED SSL FILE!              @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
Permissions 0664 for '/home/dong/ceres-combineharvester/mozilla-ca/cacert.pem' are too open. Expected 0644
One or more SSL files were found with permission issues.
Run `ceres init --fix-ssl-permissions` to fix issues.
Traceback (most recent call last):
  File "/home/dong/ceres-combineharvester/venv/bin/ceres", line 33, in <module>
    sys.exit(load_entry_point('ceres-blockchain', 'console_scripts', 'ceres')())
  File "/home/dong/ceres-combineharvester/ceres/cmds/ceres.py", line 144, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/home/dong/ceres-combineharvester/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/dong/ceres-combineharvester/ceres/cmds/plots.py", line 190, in add_cmd
    add_plot_directory(ctx.obj["root_path"], final_dir)
  File "/home/dong/ceres-combineharvester/ceres/plotting/util.py", line 74, in add_plot_directory
    if str(Path(str_path).resolve()) not in get_plot_directories(root_path, config):
  File "/home/dong/ceres-combineharvester/ceres/plotting/util.py", line 57, in get_plot_directories
    return config["plot_directories"]
KeyError: 'plot_directories'
```
I tried to add `['harvester']` after config to fix the error message, but I am not sure whether this would successfully add the directory. To check it, however, I get KeyError on `harvester` when running `ceres plots show`:
```
Traceback (most recent call last):
  File "venv/bin/ceres", line 33, in <module>
    sys.exit(load_entry_point('ceres-blockchain', 'console_scripts', 'ceres')())
  File "/ceres-combineharvester/ceres/cmds/ceres.py", line 144, in main
    cli()  # pylint: disable=no-value-for-parameter
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/ceres-combineharvester/venv/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/ceres-combineharvester/ceres/cmds/plots.py", line 212, in show_cmd
    show_plots(ctx.obj["root_path"])
  File "/ceres-combineharvester/ceres/cmds/plots.py", line 23, in show_plots
    for str_path in get_plot_directories(root_path):
  File "/ceres-combineharvester/ceres/plotting/util.py", line 58, in get_plot_directories
    return config['harvester']["plot_directories"]
KeyError: 'harvester'
```
By the way, why is it still looking for "chia_ca.crt" which is set in `ceres/util/initial-config.yaml` and should be fixed.

**Comment by hulatang** [comment]
currently, you should add plot directories manually

open file ~/.ceres/mainnet/config/coins_config.yaml


plot_directories:

- /home/your/plot/path/0001

- /home/your/plot/path/0002

- /home/your/plot/path/0003

**Comment by hulatang** [comment]
.different function currently load config attributes in different config files
will be integrated into one config file.
ceres/util/initial-config.yaml is just a template for ceres initializition.

after ceres init
there will be two config files under ~/.ceres
1. ~/.ceres/mainnet/config/config.yaml
this file is derived from initial-config.yaml, only plot_directories is active

2. ~/.ceres/mainnet/config/coins_config.yaml
some configure related to farmer is set in this file

all will be integrated into one file in future

Thank you
