### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by Basstler1** [hulatang/ceres-combineharvester#17]
Windows Client:

All Steps done. But i cannot starting harvester

Error below:

Traceback (most recent call last):
  File "C:\Users\RG\develop\ceres-combineharvester\venv\Lib\site-packages\ceres\server\start_harvester.py", line 74, in <module>
  File "C:\Users\RG\develop\ceres-combineharvester\venv\Lib\site-packages\ceres\server\start_harvester.py", line 68, in main
  File "C:\Users\RG\develop\ceres-combineharvester\venv\Lib\site-packages\ceres\server\start_harvester.py", line 47, in service_kwargs_for_harvester
  File "ceres\harvester\harvester_api.py", line 30, in __init__
  File "ceres\util\ceres_all_coins_config.py", line 33, in get_all_coins_config_constants
  File "ceres\util\ceres_all_coins_config.py", line 50, in get_coin_default_constants
  File "importlib\__init__.py", line 127, in import_module
  File "<frozen importlib._bootstrap>", line 1030, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1007, in _find_and_load
  File "<frozen importlib._bootstrap>", line 984, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ceres.consensus.all_coins_default_constants.cryptodoge_default_constants'
[8068] Failed to execute script 'start_harvester' due to unhandled exception!

**Comment by hulatang** [comment]
will be fixed.
Thanks
